<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>Upkilo.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fido2" Version="4.0.1" />
    <PackageReference Include="MediatR" Version="12.5.0" />
  </ItemGroup>

</Project>

